Bugfix and colors
qminer/qminer pull request #655
Opened 2021-02-17 13:15 UTC by blazf

2021-02-17 19:31 UTC, rupnikj approved these changes

2021-02-18 07:37 UTC, ErikNovak commented on src/glib/base/ut.cpp
> +// CODE	   COLOR
Change tabs into spaces.

2021-02-18 07:39 UTC, ErikNovak commented on src/glib/base/ut.cpp
> +void TColorNotify::OnStatus(const TStr& MsgStr) {
Requires consistent number of indentation spaces. The rest of the code has 4 spaces.

2021-02-18 07:39 UTC, ErikNovak commented on src/glib/base/ut.cpp
> -	Notify->OnStatus(TStr::Fmt("[%s %s] %s",
Change tabs into 4 spaces.

2021-02-18 07:40 UTC, ErikNovak commented on src/glib/base/ut.h
> +enum class TColorNotifyType {
Requires consistent number of indentation spaces. The rest of the code has 4 spaces.

2021-02-18 07:42 UTC, ErikNovak requested changes
Requested spacing changes:
- Tabs to spaces.
- Consistent number of spacing throughout the file (4 spaces for indentation).

2021-02-19 09:52 UTC, ErikNovak approved these changes

2021-02-19 09:52 UTC, merged